include $(GOROOT)/src/Make.inc

all: primes primespeed

primes: primes.go
	$(GC) primes.go && $(LD) -o primes primes.$(O)

primespeed: primespeed.go
	$(GC) primespeed.go && $(LD) -o primespeed primespeed.$(O)

clean:
	rm primes primespeed
